import { colors, defaultTheme, type Theme } from './tokens';

export type ThemeMode = 'light' | 'dark';

/** Semantic roles for host surfaces. Kept here so consumers never copy the skin. */
export const appearanceColors = {
    light: {
        canvas: colors.bg,
        surface: '#fffaf0',
        surfaceContainer: '#f7f1e6',
        surfaceElevated: '#fffaf0',
        surfaceMuted: colors.bgSecondary,
        surfaceOverlay: '#fffaf0',
        onSurface: colors.text,
        onSurfaceMuted: '#725d42',
        primary: colors.primary,
        onPrimary: '#3d3428',
        primaryContainer: colors.primaryBg,
        onPrimaryContainer: '#315c50',
        secondary: '#725d42',
        onSecondary: '#fffaf0',
        secondaryContainer: '#eee1c9',
        onSecondaryContainer: '#614728',
        tertiary: colors.warning,
        onTertiary: '#3d3428',
        border: colors.border,
        borderStrong: colors.borderHover,
        divider: colors.borderLight,
        focus: '#996600',
        selection: '#d6eee2',
        success: '#3d761a',
        warning: '#8a6500',
        error: '#b33939',
        info: '#315c50',
    },
    dark: {
        canvas: '#20251e',
        surface: '#2b3328',
        surfaceContainer: '#343e30',
        surfaceElevated: '#394334',
        surfaceMuted: '#30392c',
        surfaceOverlay: '#2b3328',
        onSurface: '#f4ebdd',
        onSurfaceMuted: '#cec3af',
        primary: '#6bdac8',
        onPrimary: '#173c32',
        primaryContainer: '#254c43',
        onPrimaryContainer: '#c4f3e6',
        secondary: '#dfc69b',
        onSecondary: '#3d3428',
        secondaryContainer: '#49432f',
        onSecondaryContainer: '#f3e4c7',
        tertiary: colors.warning,
        onTertiary: '#3d3428',
        border: '#59634e',
        borderStrong: '#9ca783',
        divider: '#47513e',
        focus: colors.focus,
        selection: '#365c4a',
        success: '#b0d785',
        warning: '#f5d479',
        error: '#ffaaa0',
        info: '#a1dfd0',
    },
} as const;

export function resolveNativeTheme(mode: ThemeMode = 'light'): Theme {
    if (mode === 'light') return defaultTheme;
    const palette = appearanceColors.dark;
    return {
        ...defaultTheme,
        colors: {
            ...colors,
            primary: palette.primary,
            primaryHover: '#95eadb',
            primaryActive: '#54bba9',
            primaryBg: palette.primaryContainer,
            text: palette.onSurface,
            textSecondary: palette.onSurfaceMuted,
            textDisabled: '#929782',
            bg: palette.surface,
            bgSecondary: palette.surfaceContainer,
            bgDisabled: palette.surfaceMuted,
            border: palette.border,
            borderHover: palette.borderStrong,
            borderLight: palette.divider,
            focus: palette.focus,
            success: palette.success,
            warning: palette.warning,
            error: palette.error,
            errorActive: '#a53d37',
            mask: 'rgba(0, 0, 0, 0.6)',
        },
    };
}
